### Mostrar todo el contenido
GET http://localhost:3008/contenido
Content-Type: application/json

### Traer contenido por id
GET http://localhost:3008/contenido/10
Content-Type: application/json

### Filtrar por título, género o categoría.
GET http://localhost:3008/filtrar?genero=Drama
Content-Type: application/json
###
GET http://localhost:3008/filtrar?titulo=Riverdale
Content-Type: application/json
###
GET http://localhost:3008/filtrar?categoria=Serie
Content-Type: application/json

### Agregar nuevo contenido
POST http://localhost:3008/nuevocontenido

Content-Type: application/json

{
  "titulo": "Nueva películaaaa",
  "poster": "nueva_pelicula.jpg",
  "busqueda": "Nueva película, acción, aventura",
  "resumen": "Resumen de la nueva película",
  "temporadas":2 ,
  "duracion": null,
  "trailer": "https://youtube.com/nueva_pelicula",
  "categoria_id": 2,               // ID de la categoría (asegúrate de que esta categoría exista en la tabla `categorias`)
  "actores": [1, 2],               // IDs de los actores (asegúrate de que estos actores existan en la tabla `actores`)
  "generos": [1, 2]                // IDs de los géneros (asegúrate de que estos géneros existan en la tabla `generos`)
}


### Actualizar un contenido por ID
PUT http://localhost:3008/update/44
Content-Type: application/json

{
  "titulo": "Título actualizado de la película",
  "poster": "/posters/actualizado.jpg",
  "busqueda": "Película actualizada, acción, drama",
  "resumen": "Nuevo resumen de la película actualizada",
  "temporadas": 2,
  "duracion": "130 minutos",
  "trailer": "https://youtube.com/pelicula_actualizada",
  "categoria_id": 1,               // ID de la nueva categoría (si se desea actualizar)
  "actores": [2, 3],               // IDs de los nuevos actores (reemplazará los actores anteriores)
  "generos": [1, 3]                // IDs de los nuevos géneros (reemplazará los géneros anteriores)
}

### Eliminar un contenido por ID
DELETE http://localhost:3008/delete/id
Content-Type: application/json